-- AlterTable
ALTER TABLE "users" ADD COLUMN     "monthlySpending" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalBalance" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalSavings" DOUBLE PRECISION NOT NULL DEFAULT 0;
